export default [
  {
    id: 1,
    clientName: "Jeff",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 30,
    sound: 200,
    temp: 20,
    status: "safe",
  },
  {
    id: 2,
    clientName: "Alex",
    date: new Date(),
    dateFrom: new Date("2021-07-07"),
    dateTo: new Date("2021-10-07"),
    percentage: 80,
    sound: 230,
    temp: 32,
    status: "critical",
  },
  {
    id: 3,
    clientName: "Jim",
    date: new Date(),
    dateFrom: new Date("2021-01-07"),
    dateTo: new Date("2021-03-07"),
    percentage: 50,
    sound: 100,
    temp: 32,
    status: "warning",
  },
  {
    id: 4,
    clientName: "Yong",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 31,
    sound: 210,
    temp: 35,
    status: "warning",
  },
  {
    id: 5,
    clientName: "Kira",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 65,
    sound: 450,
    temp: 20,
    status: "safe",
  },
  {
    id: 6,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 32,
    status: "critical",
  },
  {
    id: 7,
    clientName: "Kira",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 65,
    sound: 450,
    temp: 21,
    status: "safe",
  },
  {
    id: 8,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 32,
    status: "critical",
  },
  {
    id: 9,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 24,
    status: "safe",
  },
  {
    id: 10,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 22,
    status: "safe",
  },
  {
    id: 11,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 22,
    status: "safe",
  },
  {
    id: 12,
    clientName: "Nathan",
    date: new Date(),
    dateFrom: new Date(),
    dateTo: new Date(),
    percentage: 80,
    sound: 370,
    temp: 22,
    status: "safe",
  },
];
